### ISSUE TITLE
Notebook Assignment Notice 

### ISSUE THREAD

**Issue by ucalyptus** [explore-ml-iemk/ML-Summit-Workshops#1]
00. WEBINAR 1: Anaconda Installation, Familiarizing Colab and some Python Basics 
     - [x] Completed . Webinar on 20 feb
- [Notebooks are here](https://drive.google.com/open?id=1gOhFjk_ja4eKjYp8zHG20Nnxy-Lr1xCn)
------------------------------------
0. Numpy, Matplotlib ,Seaborn and Pandas @prateekmaj21  @shivamdn9 
    - [x] Completed . Deadline 20 feb . Workshop on 23 feb
------------------------------------
0. WEBINAR 2 : Cover up advanced topics of pandas and matplotlib
    - [x] Completed . Deadline 22 feb . Webinar on 25 feb
------------------------------------
1. Linear, Logistic Regression  @prateekmaj21 @Sgsouham
    - [x] Completed. Deadline 23 feb. Workshop on 1st March
------------------------------------
2. Decision Tree classifier and Decision Tree Regressor @shatadru99 
    Random Forest @shivishbrahma 
    - [x] WIP Deadline on 5th March. Workshop on 7th March
3. Support Vector Machines @shatadru99 
    - [x] WIP Deadline on 5th March. Workshop on 7th March
------------------------------------
4. XGBOOST, CATBOOST @shivishbrahma 
    - [x] WIP Deadline on 6th March. Workshop on 8th March
5. K nearest Neighbour  @shatadru99 or  @prateekmaj21 
    - [x] WIP Deadline on 6th March. Workshop on 8th March
------------------------------------
6. Artificial Neural Networks @Palspal98 
    - [ ] WIP Deadline on 1st March. Workshop on 21th March

7. Convolutional Neural Networks @Palspal98 
    - [ ] WIP Deadline on 8th March. Workshop on 21th March
------------------------------------
8. Make a submission on Kaggle: Tutorial Session on how to participate in Kaggle competitions @ucalyptus 
    - [ ] WIP Deadline on 21st March. Workshop on 28th March
9. Transfer Learning and Model Quantization post training. @ucalyptus 
    - [ ] WIP Deadline on 21st March. Workshop on 28th March
------------------------------------

**Comment by ucalyptus** [comment]
Mention which notebooks who wants to do here . I will dynamically change the above list to assign.

**Comment by prateekmaj21** [comment]
K nearest neighbour

**Comment by ayanujju** [comment]
Decision Tree classifier and Decision Tree Regressor

**Comment by shatadru99** [comment]
Decision tree and decision regressor
And, support vector machine

**Comment by Palspal98** [comment]
CNN

**Comment by ucalyptus** [comment]
@Nibba2018 I'll assign you the webinars, cool?

**Comment by ucalyptus** [comment]
@Nibba2018 can you work along with @prateekmaj21 on Workshop 1 and @shivishbrahma on Workshop 4 ?

**Comment by Nibba2018** [comment]
@ucalyptus which workshops and Webinar exactly?

**Comment by ucalyptus** [comment]
They are named numerically. Check 4 for Xgboost and 1 for logistic linear one.

**Comment by ucalyptus** [comment]
For webinar check webinar 2. Prateek is working on the basic functions notebook's of pd, np, plt and sns. Add the lesser known functions as content for webinar. Will discuss more on this on WhatsApp tomorrow morning.

**Comment by Nibba2018** [comment]
@ucalyptus  Sure will work on them 👍

**Comment by prateekmaj21** [comment]
@Nibba2018 can we  meet tomorrow after college, need to sort some things out regarding sunday.

**Comment by ucalyptus** [comment]
@shivishbrahma @ayanujju @shatadru99 @prateekmaj21 take note of deadlines for Workshop 3, 4 notebooks. Deadlines extended to 1st March. Cannot delay further.

**Comment by shivishbrahma** [comment]
since @ayanujju isn't replying... I will be helping @shatadru99 and @prateekmaj21 on both days for workshops on 7th March and 8th March. Plz add on 8th March Random forest after @prateekmaj21 's talk..
